version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  test-unit:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run unit tests
          command: npm run test:unit

  test-component:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run component tests
          command: npm run test:component

  test-docker:
   machine: true
   steps:
     - checkout
    #  Get image from github packages and curl to test api is working
     - run: docker pull ghcr.io/jonathangoulding/express-api-template:main
     - run: docker run -p 3000:3000 -d ghcr.io/jonathangoulding/express-api-template:main
     - run: curl localhost:3000/api/events

  deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Deploy dummy
          command: echo "Deploy"

workflows:
  CI CD Pipeline:
    jobs:
      - test-unit
      - test-component
      - test-docker
      - deploy:
              requires:
                - "test-docker"
                - "test-unit"
                - "test-component"
