version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  test-unit:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run unit tests
          command: npm run test:unit

  test-component:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run component tests
          command: npm run test:component

  docker:
   machine: true
   steps:
     - checkout
    #  - run: |
    #      echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
        #  docker run -d --name db company/proprietary-db:1.2.3

     # build the application image
     - run: docker pull ghcr.io/jonathangoulding/express-api-template:main

     # deploy the image
     - run: docker run -p 3000:3000 -d ghcr.io/jonathangoulding/express-api-template:main
     - run: curl localhost:3000/api/events

  deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Deploy dummy
          command: echo "Deploy"

workflows:
  CI CD Pipeline:
    jobs:
      - test-unit
      - test-component
      - docker
      - deploy:
              requires:
                - "test-unit"
                - "test-component"
